const aliases={sku:["sku","seller-sku","seller sku","商家sku","卖家sku"],errorCode:["error-code","error code","errorcode","错误代码","错误码"],message:["error-message","error message","message","错误信息","错误描述","原因"],rowNumber:["original-record-number","record number","row number","line number","行号","原始行号"],attribute:["attribute-name","attribute name","field-name","field name","字段","属性"],errorType:["error-type","error type","type","错误类型"]};
const rules={
"8541":["商品编码与现有 ASIN 信息冲突","high",["external_product_id","brand","item_name","manufacturer"],"上传信息与亚马逊目录中已有 ASIN 的关键属性不一致，通常会阻断创建或更新。",["确认这个 SKU 是要匹配已有 ASIN，还是创建全新 ASIN。","检查 UPC/EAN/ASIN 是否填错，尤其是复制模板时遗留的商品编码。","对比品牌、标题、制造商、颜色、尺寸、型号等关键字段。","如果目录信息被锁定，准备产品包装图、品牌授权或官网链接后联系 Seller Support。"]],
"99010":["缺少必填字段","high",["item_name","brand","product_type","recommended_browse_nodes"],"模板要求的必填属性没有填写，或字段名/列位置不符合当前分类模板。",["根据报告中的 attribute-name 找到对应模板列。","补齐标题、品牌、分类、商品类型、变体主题等必填字段。","确认使用的是当前站点和当前分类的最新版模板。","保存为制表符分隔文本后重新上传。"]],
"90112":["字段值不符合模板要求","medium",["size_name","color_name","fulfillment_channel","condition_type"],"字段值可能不在允许枚举范围内，或格式与模板要求不一致。",["查看错误信息中指向的字段名。","在模板的 Data Definitions 或 Valid Values 页确认允许值。","避免中文标点、额外空格、大小写不一致和自造枚举值。","只修改报错 SKU 后重新上传，确认错误是否消失。"]],
"8560":["SKU 创建失败或缺少关键信息","high",["sku","product_type","item_name","external_product_id"],"亚马逊无法用当前行创建 SKU，常见原因是商品类型、编码、分类或必填属性缺失。",["确认 SKU、product_type、item_name、brand 已填写。","检查商品编码类型和值是否匹配，例如 UPC/EAN/ASIN。","如果是无编码商品，确认是否已获 GTIN 豁免。","优先用最少字段创建测试 SKU，再逐步补充属性。"]],
"90244":["变体关系或父子体字段错误","high",["parentage","parent_sku","relationship_type","variation_theme"],"父体、子体、variation_theme 或 relationship_type 不一致。",["确认父体行 parentage 为 parent，子体行为 child。","子体必须填写 parent_sku，并指向同一个父体 SKU。","父体和所有子体使用同一个 variation_theme。","变体属性如 color/size 必须在每个子体中填写且互不冲突。"]],
"8036":["商品编码无效","high",["external_product_id","external_product_id_type"],"UPC、EAN、JAN、ISBN 或 ASIN 格式不合法，或编码类型和值不匹配。",["检查 external_product_id_type 是否与编码长度和格式匹配。","删除编码中的空格、连字符和不可见字符。","确认 UPC/EAN 来自 GS1 或合法来源。","如果没有商品编码，先确认该分类是否可申请 GTIN 豁免。"]],
"8008":["字段长度或格式错误","medium",["item_name","bullet_point","generic_keywords","description"],"字段内容超出长度限制，或包含模板不接受的格式。",["按错误报告定位字段，先减少标题、五点、Search Terms 的长度。","移除 HTML、特殊符号、重复空格和不可见字符。","确认数字、日期、货币、尺寸单位使用模板要求的格式。","重新导出为 UTF-8 文本文件后上传。"]],
"13013":["图片或图片链接问题","medium",["main_image_url","other_image_url1","swatch_image_url"],"图片 URL 无法访问、格式不支持、链接重定向异常，或图片不符合亚马逊要求。",["在无登录浏览器窗口打开图片 URL，确认能直接访问。","使用 https 链接，避免短链、网盘链接和需要权限的链接。","确认主图为白底、足够清晰，且文件格式为 JPG/PNG 等常规格式。","替换图片链接后重新上传对应 SKU。"]],
"20000":["通用处理失败","medium",["feed","template","encoding"],"报告没有给出明确字段，可能与模板版本、文件编码、站点分类或系统处理有关。",["确认模板来自当前站点、当前分类和最新 Seller Central。","只保留 1-3 个报错 SKU 做最小复现文件。","检查文件编码、分隔符、列头是否被 Excel 改动。","若最小文件仍失败，带处理报告联系 Seller Support。"]],
"8058":["品牌、制造商或分类属性冲突","medium",["brand","manufacturer","product_type","model_number"],"品牌、制造商、型号或分类属性与亚马逊目录记录不一致。",["确认品牌名拼写与 Brand Registry 或目录 ASIN 保持一致。","对比同 ASIN 页面上的品牌、制造商、型号和分类。","不要在 brand 字段里填写店铺名、卖点或无关词。","如目录信息错误，准备证明材料开 Case 请求修正。"]]
};
const sampleReport=`sku\terror-code\terror-message\tattribute-name\toriginal-record-number
SKU-RED-001\t8541\tThe value provided conflicts with the Amazon catalog.\texternal_product_id\t12
SKU-RED-002\t99010\tA value is required for item_name.\titem_name\t13
SKU-BLUE-003\t90244\tThe child SKU does not match the variation relationship.\tparent_sku\t19
SKU-GREEN-004\t13013\tMain image URL cannot be accessed.\tmain_image_url\t21
SKU-GREEN-004\t8008\tThe value exceeds the maximum allowed length.\tgeneric_keywords\t22
SKU-GOLD-005\t90112\tThe submitted value is not an accepted value.\tcondition_type\t25`;
const state={errors:[],diagnosis:null,currentView:"code",fileName:""};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const els={fileInput:$("#fileInput"),chooseFile:$("#chooseFile"),dropzone:$("#dropzone"),loadSample:$("#loadSample"),clearAll:$("#clearAll"),results:$("#results"),summaryCards:$("#summaryCards"),errorList:$("#errorList"),tabButtons:$$(".tab-button"),copyMarkdown:$("#copyMarkdown"),downloadCsv:$("#downloadCsv"),ruleGrid:$("#ruleGrid"),toast:$("#toast")};
const h=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
const norm=v=>String(v||"").trim().toLowerCase().replace(/\uFEFF/g,"").replace(/[_\s]+/g," ").replace(/\s*-\s*/g,"-");
const allAliases=Object.values(aliases).flat().map(norm), supported=new Set(["txt","csv","tsv"]);
function rule(code){const r=rules[code]||["未知错误码","low",["查看原始报告字段"],"规则库暂未覆盖这个错误码，请先依据原始错误信息定位字段。",["复制错误码和完整错误信息，在 Seller Central 帮助中心搜索。","检查报告中的 SKU、字段名、行号和原始上传文件。","如果同一错误影响多个 SKU，先用一个 SKU 做最小复现文件。","把最小复现文件和 Processing Report 一起提交给 Seller Support。"]];return{title:r[0],severity:r[1],likelyFields:r[2],explanation:r[3],fixSteps:r[4]};}
function splitLine(line,delimiter){const cells=[];let cur="",q=false;for(let i=0;i<line.length;i++){const c=line[i],n=line[i+1];if(c==='"'&&q&&n==='"'){cur+='"';i++;continue;}if(c==='"'){q=!q;continue;}if(c===delimiter&&!q){cells.push(cur.trim());cur="";continue;}cur+=c;}cells.push(cur.trim());return cells;}
function delimiter(line){return ["\t",",",";","|"].map(d=>[d,splitLine(line,d).length]).sort((a,b)=>b[1]-a[1])[0][0];}
function headerScore(line){const d=delimiter(line);return splitLine(line,d).map(norm).reduce((s,c)=>s+(c.length>1&&allAliases.some(a=>c===a||c.includes(a)||a.includes(c))?1:0),0);}
function parseDelimited(text){if(text.length>2500000)throw new Error("文件内容过大，请先导出较小的 Processing Report 或只保留报错行后再试。");const lines=text.replace(/\r\n/g,"\n").replace(/\r/g,"\n").split("\n").filter(l=>l.trim());if(lines.length<2)throw new Error("报告至少需要包含表头和一行错误数据。");const headerIndex=lines.slice(0,30).map((line,index)=>({index,score:headerScore(line)})).sort((a,b)=>b.score-a.score||a.index-b.index)[0];const start=headerIndex.score>=2?headerIndex.index:0;const d=delimiter(lines[start]),headers=splitLine(lines[start],d),data=lines.slice(start+1);if(!data.length)throw new Error("识别到表头，但没有找到错误数据行。");return{headers,rows:data.map(line=>{const cells=splitLine(line,d);return headers.reduce((row,head,i)=>{row[head]=cells[i]||"";return row;},{});})};}
function findCol(headers,type){const normalized=headers.map(raw=>({raw,norm:norm(raw)})),keys=aliases[type].map(norm);return (normalized.find(h=>keys.includes(h.norm))||normalized.find(h=>keys.some(k=>h.norm.includes(k)||k.includes(h.norm)))||{}).raw||null;}
function toErrors(parsed){const c={sku:findCol(parsed.headers,"sku"),errorCode:findCol(parsed.headers,"errorCode"),message:findCol(parsed.headers,"message"),rowNumber:findCol(parsed.headers,"rowNumber"),attribute:findCol(parsed.headers,"attribute"),errorType:findCol(parsed.headers,"errorType")};if(!c.errorCode&&!c.message)throw new Error("没有识别到 error-code 或 error-message 字段，请确认文件是 Amazon Processing Report。");return parsed.rows.map((row,index)=>{const fallback=Object.values(row).join(" ").match(/\b\d{4,5}\b/)?.[0]||"UNKNOWN",code=c.errorCode?row[c.errorCode]:fallback;return{sku:c.sku?row[c.sku]||"未识别 SKU":"未识别 SKU",rowNumber:c.rowNumber?row[c.rowNumber]||String(index+2):String(index+2),errorCode:String(code||fallback).trim(),errorType:c.errorType?row[c.errorType]:"",message:c.message?row[c.message]||"":"",attribute:c.attribute?row[c.attribute]||"":"",raw:row};}).filter(x=>x.errorCode||x.message);}
const unique=a=>[...new Set(a.filter(Boolean))];
function group(items,getKey){return items.reduce((g,i)=>{const k=getKey(i)||"未识别";(g[k] ||= []).push(i);return g;},{});}
function diagnose(errors){const sev=errors.reduce((a,e)=>{a[rule(e.errorCode).severity]++;return a;},{high:0,medium:0,low:0});return{summary:{totalErrors:errors.length,affectedSkus:unique(errors.map(e=>e.sku)).length,...sev},byCode:group(errors,e=>e.errorCode),bySku:group(errors,e=>e.sku),byRow:group(errors,e=>e.rowNumber)};}
const sevLabel=s=>({high:"高风险",medium:"中风险",low:"低风险"}[s]||"待确认");
function setActiveView(view){state.currentView=view;els.tabButtons.forEach(b=>{const active=b.dataset.view===view;b.classList.toggle("active",active);b.setAttribute("aria-selected",String(active));});}
function toast(msg){els.toast.textContent=msg;els.toast.classList.add("show");setTimeout(()=>els.toast.classList.remove("show"),2400);}
function renderSummary(){const s=state.diagnosis.summary,cards=[["错误总数",s.totalErrors,"报告中识别到的错误行"],["影响 SKU",s.affectedSkus,"需要回到模板修复的商品"],["高风险",s.high,"优先处理，会阻断上传"],["中低风险",s.medium+s.low,"格式、图片或待确认问题"]];els.summaryCards.innerHTML=cards.map(([l,v,t])=>`<article class="summary-card"><span>${l}</span><strong>${v}</strong><small>${t}</small></article>`).join("");}
function caseText(e,r){return`Subject: Help needed with Amazon flat file upload error ${e.errorCode||""}\n\nHello Amazon Seller Support,\n\nI received error ${e.errorCode||""} when uploading my inventory flat file.\n\nAffected SKU: ${e.sku||""}\nOriginal record number: ${e.rowNumber||""}\nAttribute: ${e.attribute||""}\nError message: ${e.message||""}\n\nI have checked the relevant fields, including ${r.likelyFields.join(", ")}.\nCould you please help confirm which catalog attribute or template requirement is causing this error?\n\nThank you.`;}
function card(title,subtitle,items,code){const r=rule(code||items[0]?.errorCode),skus=unique(items.map(i=>i.sku)),rows=unique(items.map(i=>i.rowNumber)),attrs=unique(items.map(i=>i.attribute)).slice(0,8),primary=items[0]||{};return`<article class="error-card"><div class="error-card-header"><div><h3>${h(title)}</h3><p>${h(subtitle)}</p></div><span class="severity ${h(r.severity)}">${sevLabel(r.severity)}</span></div><div class="error-body"><div class="fix-list"><h4>${h(r.title)}</h4><p>${h(r.explanation)}</p><ol>${r.fixSteps.map(s=>`<li>${h(s)}</li>`).join("")}</ol></div><div class="affected-list"><h4>影响范围</h4><div class="pill-row">${skus.slice(0,12).map(s=>`<span class="pill">SKU ${h(s)}</span>`).join("")}</div><div class="pill-row">${rows.slice(0,12).map(r=>`<span class="pill">行 ${h(r)}</span>`).join("")}</div><div class="pill-row">${(attrs.length?attrs:r.likelyFields).map(f=>`<span class="pill">${h(f)}</span>`).join("")}</div><div class="case-box"><h4>Seller Support Case 话术</h4><textarea readonly>${h(caseText(primary,r))}</textarea></div></div></div></article>`;}
function renderErrors(){const view=state.currentView,d=state.diagnosis,groups=view==="sku"?d.bySku:view==="row"?d.byRow:d.byCode,weight={high:3,medium:2,low:1};els.errorList.innerHTML=Object.entries(groups).sort((a,b)=>{const ar=rule(view==="code"?a[0]:a[1][0]?.errorCode),br=rule(view==="code"?b[0]:b[1][0]?.errorCode);return weight[br.severity]-weight[ar.severity]||b[1].length-a[1].length;}).map(([key,items])=>{if(view==="sku")return card(`SKU ${key}`,`包含 ${items.length} 条错误，错误码：${unique(items.map(i=>i.errorCode)).join(", ")}`,items,items[0]?.errorCode);if(view==="row"){const first=items[0];return card(`原始行号 ${key}`,`${first.sku} · Error ${first.errorCode}`,items,first.errorCode);}const r=rule(key);return card(`Error ${key}`,`${r.title} · 影响 ${items.length} 行`,items,key);}).join("");}
function renderRules(){els.ruleGrid.innerHTML=Object.entries(rules).map(([code,r])=>`<article class="rule-card"><strong>Error ${h(code)}</strong><p>${h(r[0])}</p></article>`).join("");}
function processText(text,fileName="示例报告"){const errors=toErrors(parseDelimited(text));if(!errors.length)throw new Error("没有识别到错误行。请确认报告中包含 error-code 或 error-message。");state.errors=errors;state.diagnosis=diagnose(errors);state.fileName=fileName;setActiveView("code");els.results.classList.remove("hidden");renderSummary();renderErrors();els.results.scrollIntoView({behavior:"smooth",block:"start"});toast(`已解析 ${errors.length} 条错误`);}
async function readFile(file){const ext=file.name.split(".").pop().toLowerCase();if(!supported.has(ext)){toast("第一版暂不支持该格式，请上传 .txt / .csv / .tsv");return;}if(file.size>2*1024*1024){toast("文件过大，请上传 2MB 以内的 Processing Report");return;}processText(await file.text(),file.name);}
function buildMarkdown(){if(!state.errors.length)return"";const lines=["# Amazon Flat File 错误修复清单","",`文件：${state.fileName}`,`错误总数：${state.diagnosis.summary.totalErrors}`,`影响 SKU：${state.diagnosis.summary.affectedSkus}`,""];Object.entries(state.diagnosis.byCode).forEach(([code,items])=>{const r=rule(code);lines.push(`## Error ${code} ${r.title}`,`严重程度：${sevLabel(r.severity)}`,`影响 SKU：${unique(items.map(i=>i.sku)).join(", ")}`,`建议检查字段：${r.likelyFields.join(", ")}`);r.fixSteps.forEach((s,i)=>lines.push(`${i+1}. ${s}`));lines.push("");});return lines.join("\n");}
function downloadCsv(){if(!state.errors.length)return;const rows=[["sku","rowNumber","errorCode","severity","attribute","message","recommendedFields"],...state.errors.map(i=>{const r=rule(i.errorCode);return[i.sku,i.rowNumber,i.errorCode,sevLabel(r.severity),i.attribute,i.message,r.likelyFields.join(" | ")];})];const csv=rows.map(row=>row.map(cell=>`"${String(cell||"").replace(/"/g,'""')}"`).join(",")).join("\n"),url=URL.createObjectURL(new Blob([`\uFEFF${csv}`],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download="amazon-flat-file-fix-list.csv";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function clearAll(){state.errors=[];state.diagnosis=null;state.fileName="";els.fileInput.value="";els.results.classList.add("hidden");els.errorList.innerHTML="";els.summaryCards.innerHTML="";toast("已清空");}
function copyText(text){const fallback=()=>{const t=document.createElement("textarea");t.value=text;t.readOnly=true;t.style.position="fixed";t.style.left="-9999px";document.body.appendChild(t);t.select();const ok=document.execCommand("copy");t.remove();if(!ok)throw new Error("复制失败，请手动选择结果文本复制。");};return navigator.clipboard?.writeText?navigator.clipboard.writeText(text).catch(fallback):Promise.resolve(fallback());}
els.chooseFile.addEventListener("click",()=>els.fileInput.click());
els.fileInput.addEventListener("change",e=>{const f=e.target.files?.[0];if(f)readFile(f).catch(err=>toast(err.message));});
["dragenter","dragover"].forEach(n=>els.dropzone.addEventListener(n,e=>{e.preventDefault();els.dropzone.classList.add("dragover");}));
["dragleave","drop"].forEach(n=>els.dropzone.addEventListener(n,e=>{e.preventDefault();els.dropzone.classList.remove("dragover");}));
els.dropzone.addEventListener("drop",e=>{const f=e.dataTransfer.files?.[0];if(f)readFile(f).catch(err=>toast(err.message));});
els.dropzone.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();els.fileInput.click();}});
els.loadSample.addEventListener("click",()=>processText(sampleReport,"sample-processing-report.tsv"));
els.clearAll.addEventListener("click",clearAll);
els.tabButtons.forEach(b=>b.addEventListener("click",()=>{setActiveView(b.dataset.view);renderErrors();}));
els.copyMarkdown.addEventListener("click",async()=>{const text=buildMarkdown();if(!text)return;try{await copyText(text);toast("修复清单已复制");}catch(err){toast(err.message);}});
els.downloadCsv.addEventListener("click",downloadCsv);
setActiveView(state.currentView);renderRules();
