/* Amazon Flat File Diagnoser CSV/delimited export helpers. Lazy-loaded by app.js. */
function csvFormulaSafe(value){const text=String(value??""),trimmed=text.replace(/^[\uFEFF\s]+/,"");return /^[=+\-@]/.test(trimmed)?`'${text}`:text;}
function csvCell(value){const text=csvFormulaSafe(value);return`"${text.replace(/"/g,'""')}"`;}
function manualReviewCsvText(){const v=state.variation;if(!v?.manualReviewRows?.length)return"";const rows=[["sku","row","parent_sku","issue","column","fixability","reason"],...v.manualReviewRows.map(i=>[i.sku,i.rowIndex,i.parentSku,i.issue,i.column,i.fixability,i.reason])];return rows.map(row=>row.map(csvCell).join(",")).join("\n");}
function downloadManualReviewCsv(){const text=manualReviewCsvText();if(!text){toast("没有需要导出的人工复核行");return;}const base=fileSlug(state.flatFileName||"flat-file"),url=URL.createObjectURL(new Blob([`\uFEFF${text}`],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download=`amazon-manual-review-needed-${base}-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);trackEvent("manual_review_needed_csv_downloaded",{row_count:state.variation.manualReviewRows.length});}
function escapeDelimitedCell(value,d){const text=d===","?csvFormulaSafe(value):String(value??"");return text.includes(d)||text.includes('"')||text.includes("\n")?`"${text.replace(/"/g,'""')}"`:text;}
function serializeDelimited(headers,rows,d){return [headers.map(v=>escapeDelimitedCell(v,d)).join(d),...rows.map(row=>headers.map(head=>escapeDelimitedCell(row[head]||"",d)).join(d))].join("\n");}
function repairedFlatFileText(){const v=state.variation;if(!v?.repairPlan?.length)return"";const headers=[...v.parsed.headers],rows=v.parsed.rows.map(row=>({...row})),byLine=new Map(v.parsed.rows.map((row,index)=>[row._lineNumber||index+2,rows[index]]));v.repairPlan.forEach(item=>{const row=byLine.get(item.rowIndex);if(row&&item.column&&Object.prototype.hasOwnProperty.call(row,item.column))row[item.column]=item.to;});return serializeDelimited(headers,rows,v.parsed.delimiter||"\t");}
function downloadRepairedFlatFile(){const text=repairedFlatFileText();if(!text){toast("没有可自动生成的低风险修复草稿");return;}const ext=(state.flatFileName.split(".").pop()||"tsv").toLowerCase(),base=fileSlug(state.flatFileName||"flat-file"),mime=ext==="csv"?"text/csv;charset=utf-8":"text/tab-separated-values;charset=utf-8",url=URL.createObjectURL(new Blob([`\uFEFF${text}`],{type:mime})),a=document.createElement("a");a.href=url;a.download=`amazon-repaired-draft-${base}-${new Date().toISOString().slice(0,10)}.${ext}`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);trackEvent("repaired_flat_file_draft_downloaded",{fix_count:state.variation.repairPlan.length,file_extension:ext});}
