/* Amazon Flat File Diagnoser parser helpers. Lazy-loaded by app.js. */
function splitLine(line,delimiter){const cells=[];let cur="",q=false;for(let i=0;i<line.length;i++){const c=line[i],n=line[i+1];if(c==='"'&&q&&n==='"'){cur+='"';i++;continue;}if(c==='"'){q=!q;continue;}if(c===delimiter&&!q){cells.push(cur.trim());cur="";continue;}cur+=c;}cells.push(cur.trim());return cells;}
function delimiter(line){return ["\t",",",";","|"].map(d=>[d,splitLine(line,d).length]).sort((a,b)=>b[1]-a[1])[0][0];}
function headerScore(line){const d=delimiter(line);return splitLine(line,d).map(norm).reduce((s,c)=>s+(c.length>1&&allAliases.some(a=>c===a||c.includes(a)||a.includes(c))?1:0),0);}
function parseRecords(text,d){const records=[];let row=[],cur="",q=false,startLine=1,line=1;const pushCell=()=>{row.push(cur.trim());cur="";};const pushRow=()=>{pushCell();records.push({cells:row,line:startLine});row=[];startLine=line+1;};for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cur+='"';i++;continue;}if(c==='"'){q=!q;continue;}if(c===d&&!q){pushCell();continue;}if((c==="\n"||c==="\r")&&!q){if(c==="\r"&&n==="\n")i++;pushRow();line++;continue;}if(c==="\n"||c==="\r")line++;cur+=c;}if(cur||row.length)pushRow();return records.filter(r=>r.cells.some(cell=>String(cell).trim()));}
function duplicateHeaderNames(headers){const seen=new Map(),dupes=[];headers.forEach(head=>{const key=norm(head);if(!key)return;seen.set(key,(seen.get(key)||0)+1);if(seen.get(key)===2)dupes.push(head);});return dupes;}
function parseDelimited(text){if(text.length>5000000)throw new Error("文件内容过大，请先导出较小的报告或 flat file 后再试。");const physicalLines=text.replace(/\r\n/g,"\n").replace(/\r/g,"\n").split("\n").map((line,index)=>({line,index:index+1})).filter(item=>item.line.trim());if(physicalLines.length<2)throw new Error("报告至少需要包含表头和一行错误数据。");const headerPick=physicalLines.slice(0,30).map(item=>({line:item.line,lineNumber:item.index,score:headerScore(item.line)})).sort((a,b)=>b.score-a.score||a.lineNumber-b.lineNumber)[0];const d=delimiter(headerPick.score>=2?headerPick.line:physicalLines[0].line),records=parseRecords(text,d);if(records.length<2)throw new Error("报告至少需要包含表头和一行错误数据。");let headerRecordIndex=records.findIndex(r=>r.line===headerPick.lineNumber);if(headerRecordIndex<0)headerRecordIndex=headerPick.score>=2?0:0;const headers=records[headerRecordIndex].cells.map((head,index)=>index===0?String(head||"").replace(/^\uFEFF/,""):String(head||""));const duplicateHeaders=duplicateHeaderNames(headers);if(duplicateHeaders.length)throw new Error(`检测到重复表头：${duplicateHeaders.join("、")}。为避免覆盖同名列，请先删除或重命名重复列后再上传。`);const data=records.slice(headerRecordIndex+1);if(!data.length)throw new Error("识别到表头，但没有找到错误数据行。");return{headers,delimiter:d,rows:data.map(record=>{const row=headers.reduce((acc,head,i)=>{acc[head]=record.cells[i]||"";return acc;},{});Object.defineProperty(row,"_lineNumber",{value:record.line,enumerable:false});return row;})};}
function findCol(headers,type){const normalized=headers.map(raw=>({raw,norm:norm(raw)})),keys=aliases[type].map(norm);return (normalized.find(h=>keys.includes(h.norm))||normalized.find(h=>keys.some(k=>h.norm.includes(k)||k.includes(h.norm)))||{}).raw||null;}
function toErrors(parsed){const c={sku:findCol(parsed.headers,"sku"),errorCode:findCol(parsed.headers,"errorCode"),message:findCol(parsed.headers,"message"),rowNumber:findCol(parsed.headers,"rowNumber"),attribute:findCol(parsed.headers,"attribute"),errorType:findCol(parsed.headers,"errorType")};if(!c.errorCode&&!c.message)throw new Error("没有识别到 error-code 或 error-message 字段，请确认文件是 Amazon Processing Report。");return parsed.rows.map((row,index)=>{const physicalLine=row._lineNumber||index+2,codeFromColumn=c.errorCode?normalizeCode(row[c.errorCode]):"UNKNOWN",codeFromMessage=c.message?normalizeCode(row[c.message]):"UNKNOWN",code=codeFromColumn!=="UNKNOWN"?codeFromColumn:codeFromMessage;return{sku:c.sku?row[c.sku]||"未识别 SKU":"未识别 SKU",rowNumber:c.rowNumber?row[c.rowNumber]||String(physicalLine):String(physicalLine),errorCode:code,errorType:c.errorType?row[c.errorType]:"",message:c.message?row[c.message]||"":"",attribute:c.attribute?row[c.attribute]||"":"",raw:row};}).filter(x=>x.errorCode!=="UNKNOWN"||x.message);}
